### ISSUE TITLE
Unable to create folder

### ISSUE THREAD

**Issue by bhargavkonkathi** [fkoester/angular-filemanager-nodejs-bridge#4]
Error occurred while creating new folder.

**Error description** 
TypeError: Path must be a string. Received undefined    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)

Following file change will resolve issue for creating folder.
Filename causing the issue :- routes/index.js in createFolder(line 156)

**Fix for issue:-**
Replace this line(156)  **var folderPath = path.join(pathResolver.baseDir(req), req.body.params.path, req.body.params.name);**   with following line 
**var folderPath = path.join(pathResolver.baseDir(req), req.body.params.newPath);** will resolve issue.

As angular file upload will post following body while creating new folder.
Post body :{action: "createFolder", newPath: "/dsagg"} 

Thanks.

**Comment by fkoester** [comment]
Thanks for your input @bhargavkonkathi! Can you create a Pull Request for the fix?

**Comment by bhargavkonkathi** [comment]
@fkoester, Created pull request. Cheers  :smile:  :+1:
